--
-- add to the services
--

INSERT INTO `service` (`name`, `caption`, `icon`, `description`, `creator_email`, `insertion_date`, `category`, `version`, `listed`, `guest_allowed`, `ads_allowed`, `active`) 
VALUES ('citas', 'Cita Célebre', 'fas fa-quote-right', 'Muestra una cita célebre para alegrarle el día, y le permite compartirla en la Pizarra.', 'salvi@apretaste.org', current_timestamp(), 'ocio', '1', '1', '1', '1', '1');

--
-- Table structure for table `_citas`
--

CREATE TABLE `_citas` (
  `id` int(11) NOT NULL,
  `quote` varchar(500) COLLATE utf8mb4_swedish_ci NOT NULL,
  `author` varchar(50) COLLATE utf8mb4_swedish_ci NOT NULL,
  `views` int(6) NOT NULL DEFAULT 0,
  `likes` int(5) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

ALTER TABLE `_citas`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `_citas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

--
-- Table structure for table `_citas`
--

INSERT INTO _citas (quote, author) VALUES
('Los libros son compañeros dulces para el que sufre, y si no pueden llevarnos a gozar de la vida, al menos nos enseñan a soportarla.','Oliver Goldsmith'),
('La cantidad de rumores inútiles que un hombre puede soportar es inversamente proporcional a su inteligencia.','Franz Grillparzer '),
('El hombre que me da trabajo, al que tengo que sufrir, este hombre es mi dueño, llámelo como lo llame.','Henry George '),
('El hombre sano no tortura a otros, por lo general es el torturado el que se convierte en torturador.','Carl Gustav Jung'),
('La derrota tiene algo positivo: nunca es definitiva. En cambio, la victoria tiene algo negativo: jamás es definitiva.','José Saramago'),
('El trabajo obsesivo produce la locura, tanto como la pereza completa, pero con esta combinación se puede vivir.','Erich Fromm'),
('La música es sinónimo de libertad, de tocar lo que quieras y como quieras, siempre que sea bueno y tenga pasión, que la música sea el alimento del amor.','Kurt D. Cobain'),
('La música es para el alma lo que la gimnasia para el cuerpo.','Platón'),
('El mundo está lleno de pequeñas alegrías: el arte consiste en saber distinguirlas.','Li Tai-Po'),
('Pienso que una vida dedicada a la música es una vida bellamente empleada, y es a eso a lo que he dedicado la mía.','Luciano Pavarotti'),
('Si la inspiración no viene a mí salgo a su encuentro, a la mitad del camino.','Sigmund Freud'),
('No existen más que dos reglas para escribir: tener algo que decir y decirlo','Oscar Wilde'),
('La música constituye una revelación más alta que ninguna filosofía.','Ludwig van Beethoven'),
('La inspiración existe, pero tiene que encontrarte trabajando.','Pablo Picasso'),
('Los malos libros provocan malas costumbres y las malas costumbres provocan buenos libros.','René Descartes'),
('La música compone los ánimos descompuestos y alivia los trabajos que nacen del espíritu.','Miguel de Cervantes'),
('La pintura es poesía muda; la poesía pintura ciega.','Leonardo Da Vinci'),
('La finalidad del arte es dar cuerpo a la esencia secreta de las cosas, no el copiar su apariencia.','Aristóteles'),
('Si yo pinto a mi perro exactamente como es, naturalmente tendré dos perros, pero no una obra de arte.','Goethe'),
('La crítica es la fuerza del impotente.','Alphonse de Lamartine'),
('Tienen derecho a censurar los que tienen corazón para ayudar.','William Penn'),
('La inspiración existe, pero tiene que encontrarte trabajando.','Pablo Picasso'),
('La posibilidad de realizar un sueño es lo que hace que la vida sea interesante.','Paulo Coelho'),
('No que me hayas mentido, que ya no pueda creerte, eso me aterra.','Friedrich Nietzsche'),
('La verdad se corrompe tanto con la mentira como con el silencio.','Cicerón'),
('¡Qué poco cuesta construir castillos en el aire y qué cara es su destrucción!','François Mauriac'),
('Amor y deseo son dos cosas diferentes; que no todo lo que se ama se desea, ni todo lo que se desea se ama.','Miguel de Cervantes'),
('Todo lo que somos es el resultado de lo que hemos pensado; está fundado en nuestros pensamientos y está hecho de nuestros pensamientos.','Buda'),
('No tratéis de guiar al que pretende elegir por sí su propio camino.','William Shakespeare'),
('No basta decir solamente la verdad, mas conviene mostrar la causa de la falsedad.','Aristóteles'),
('Sólo es inmensamente rico aquel que sabe limitar sus deseos.','Voltaire '),
('La memoria es el único paraíso del que no podemos ser expulsados.','Jean Paul'),
('Con una mentira suele irse muy lejos, pero sin esperanzas de volver.','Proverbio judío'),
('Una mentira es como una bola de nieve; cuanto más rueda, más grande se vuelve.','Martin Lutero'),
('Vivir sus deseos, agotarlos en la vida, es el destino de toda existencia.','Henry Miller'),
('El trabajo del pensamiento se parece a la perforación de un pozo: el agua es turbia al principio, mas luego se clarifica.','Proverbio chino'),
('De vez en cuando di la verdad para que te crean cuando mientes.','Jules Renard'),
('Lo pasado ha huido, lo que esperas está ausente, pero el presente es tuyo.','Proverbio árabe'),
('El futuro tiene muchos nombres. Para los débiles es lo inalcanzable. Para los temerosos, lo desconocido. Para los valientes es la oportunidad.','Victor Hugo'),
('La memoria del corazón elimina los malos recuerdos y magnifica los buenos, y gracias a ese artificio, logramos sobrellevar el pasado.','Gabriel García Márquez '),
('El tiempo es el mejor autor: siempre encuentra un final perfecto.','Charles Chaplin'),
('El futuro pertenece a quienes creen en la belleza de sus sueños.','Eleanor Roosevelt'),
('Me interesa el futuro porque es el sitio donde voy a pasar el resto de mi vida.','Woody Allen'),
('El niño que no juega no es niño, pero el hombre que no juega perdió para siempre al niño que vivía en él y que le hará mucha falta.','Pablo Neruda '),
('Los jóvenes hoy en día son unos tiranos. Contradicen a sus padres, devoran su comida, y le faltan al respeto a sus maestros.','Sócrates'),
('De mis disparates de juventud lo que más pena me da no es el haberlos cometido, sino el no poder volver a cometerlos.','Pierre Benoit'),
('Nunca es tarde para bien hacer; haz hoy lo que no hiciste ayer.','Refrán'),
('El secreto de una buena vejez no es otra cosa que un pacto honrado con la soledad.','Gabriel García Márquez '),
('La infancia tiene sus propias maneras de ver, pensar y sentir; nada hay más insensato que pretender sustituirlas por las nuestras.','Jean Jacques Rousseau '),
('Solamente aquel que construye el futuro tiene derecho a juzgar el pasado.','Friedrich Nietzsche'),
('El problema del matrimonio es que se acaba todas las noches después de hacer el amor, y hay que volver a reconstruirlo todas las mañanas antes del desayuno.','Gabriel García Márquez '),
('Las mujeres han sido hechas para ser amadas, no para ser comprendidas.','Oscar Wilde'),
('Las batallas contra las mujeres son las únicas que se ganan huyendo.','Napoleón I'),
('De aquel que opina que el dinero puede hacerlo todo, cabe sospechar con fundamento que será capaz de hacer cualquier cosa por dinero.','Benjamin Franklin'),
('Las guerras seguirán mientras el color de la piel siga siendo más importante que el de los ojos.','Bob Marley'),
('Las mujeres necesitamos la belleza para que los hombres nos amen, y la estupidez para que nosotras amemos a los hombres.','Coco Chanel'),
('Una casa será fuerte e indestructible cuando esté sostenida por estas cuatro columnas: padre valiente, madre prudente, hijo obediente, hermano complaciente.','Confucio'),
('Los hombres construimos demasiados muros y no suficientes puentes.','Isaac Newton'),
('Quien cambia felicidad por dinero no podrá cambiar dinero por felicidad.','José Narosky '),
('Honraré la Navidad en mi corazón y procuraré conservarla durante todo el año.','Charles Dickens'),
('No podemos modelar a nuestros hijos según nuestros deseos, debemos estar con ellos y amarlos como Dios nos los ha entregado.','Goethe'),
('No hay camino para la paz, la paz es el camino.','Mahatma Gandhi'),
('La libertad de expresión es decir lo que la gente no quiere oír.','George Orwell'),
('Lo que con mucho trabajo se adquiere, más se ama.','Aristóteles'),
('Cuando me preguntaron sobre algún arma capaz de contrarrestar el poder de la bomba atómica yo sugerí la mejor de todas: La paz.','Albert Einstein'),
('No puedo parar de trabajar. Tendré toda la eternidad para descansar.','Madre Teresa de Calcuta'),
('Siempre que te pregunten si puedes hacer un trabajo, contesta que sí y ponte enseguida a aprender como se hace.','Franklin D. Roosevelt'),
('Es más fácil apoderarse del comandante en jefe de un ejército que despojar a un miserable de su libertad.','Confucio'),
('La gran pregunta que nunca ha sido contestada y a la cual todavía no he podido responder, a pesar de mis treinta años de investigación del alma femenina, es: ¿qué quiere una mujer?','Sigmund Freud'),
('El hombre ha nacido libre y por doquiera se encuentra sujeto con cadenas.','Jean Jacques Rousseau '),
('No se nos otorgará la libertad externa más que en la medida exacta en que hayamos sabido, en un momento determinado, desarrollar nuestra libertad interna.','Mahatma Gandhi'),
('La paz comienza con una sonrisa.','Madre Teresa de Calcuta'),
('La libertad no es simplemente un privilegio que se otorga; es un habito que ha de adquirirse.','David Lloyd George'),
('La mujer es un manjar digno de dioses, cuando no lo cocina el diablo.','William Shakespeare'),
('Dos cosas contribuyen a avanzar: ir más deprisa que los otros o ir por el buen camino.','René Descartes'),
('Los únicos goces puros y sin mezcla de tristeza que le han sido dados sobre la tierra al hombre, son los goces de familia.','Giuseppe Mazzini'),
('La política es el arte de servirse de los hombres haciéndoles creer que se les sirve a ellos.','Louis Dumur'),
('La multitud por sí sola nunca llega a nada si no tiene un líder que la guíe.','Hermann Keyserling'),
('La mujer, está donde le corresponde. Millones de años de evolución no se han equivocado, pues la naturaleza tiene la capacidad de corregir sus propios defectos.','Albert Einstein'),
('No existe la libertad, sino la búsqueda de la libertad, y esa búsqueda es la que nos hace libres.','Carlos Fuentes'),
('Tenemos bastante religión para odiarnos unos a otros, pero no la bastante para amarnos.','Jonathan Swift'),
('Donde mora la libertad, allí está mi patria.','Benjamin Franklin'),
('No basta con hablar de paz. Uno debe creer en ella y trabajar para conseguirla.','Eleanor Roosevelt'),
('Donde hay educación no hay distinción de clases.','Confucio'),
('El progreso y el desarrollo son imposibles si uno sigue haciendo las cosas tal como siempre las ha hecho.','Wayne W. Dyer'),
('La sociedad está bien ordenada cuando los ciudadanos obedecen a los magistrados, y los magistrados a las leyes.','Solón de Atenas'),
('Que nadie se haga ilusiones de que la simple ausencia de guerra, aun siendo tan deseada, sea sinónimo de una paz verdadera. No hay verdadera paz sino viene acompañada de equidad , verdad, justicia, y solidaridad.','Juan Pablo II'),
('¡Hay tantas cosas en la vida más importantes que el dinero! ¡Pero cuestan tanto!.','Groucho Marx'),
('La multitud obedece más a la necesidad que a la razón, y a los castigos más que al honor.','Aristóteles '),
('El mantenimiento de la paz comienza con la autosatisfacción de cada individuo.','Dalai Lama'),
('Los malos hábitos es más fácil romperlos que enmendarlos.','Quintiliano'),
('Si no estamos en paz con nosotros mismos, no podemos guiar a otros en la búsqueda de la paz.','Confucio'),
('Gobernar es el arte de crear problemas con cuya solución mantiene a la población en vilo.','Ezra Pound'),
('El dinero no da la felicidad, pero procura una sensación tan parecida, que necesita un especialista muy avanzado para verificar la diferencia.','Woody Allen'),
('Me maravillo a menudo de que la historia resulte tan pesada, porque gran parte de ella debe ser pura invención.','Jane Austen'),
('Las mujeres lo negaran o lo aceptaran, pero lo que siempre quieren es que se lo pidamos.','Ovidio'),
('En la sociedad, el hombre sensato es el primero que cede siempre. Por eso, los más sabios son dirigidos por los más necios y extravagantes.','Jean de la Bruyere'),
('Cómo tener confianza de una mujer que le dice a uno su verdadera edad. Una mujer capaz de decir esto es capaz de decirlo todo.','Oscar Wilde'),
('Nadie puede llegar a la cima armado sólo de talento. Dios da el talento; el trabajo transforma el talento en genio.','Anna Pavlova'),
('La libertad no es un fin, es un medio para desarrollar nuestras fuerzas.','Giuseppe Mazzini'),
('La primera vez que me engañes, será culpa tuya; la segunda vez, la culpa será mía.','Proverbio árabe '),
('Cuando quieres realmente una cosa, todo el Universo conspira para ayudarte a conseguirla.','Paulo Coelho'),
('Siembra un acto y cosecharás un hábito. Siembra un hábito y cosecharás un carácter. Siembra un carácter y cosecharás un destino.','Charles Reade'),
('Si buscas resultados distintos, no hagas siempre lo mismo.','Albert Einstein'),
('Cuando crezcas, descubrirás que ya defendiste mentiras, te engañaste a ti mismo o sufriste por tonterías. Si eres un buen guerrero, no te culparás por ello, pero tampoco dejarás que tus errores se repitan.','Paulo Coelho'),
('En la vida no hay premios ni castigos, sino consecuencias.','Robert Green Ingersoll'),
('Ayuda a tus semejantes a levantar su carga, pero no te consideres obligado a llevársela','Pitágoras de Samos'),
('Si lloras por haber perdido el sol, las lágrimas no te dejarán ver las estrellas.','Rabindranath Tagore'),
('Cada uno de los movimientos de todos los individuos se realizan por tres únicas razones: por honor, por dinero o por amor.','Napoleón I '),
('Los grandes espíritus siempre han encontrado una violenta oposición de parte de mentes mediocres.','Albert Einstein'),
('Tratar de olvidar a alguien es querer recordarlo para siempre.','Anónimo'),
('He fallado una y otra vez en mi vida, por eso he conseguido el éxito.','Michael Jordan'),
('Todos piensan en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo.','Alexei Tolstoi '),
('Acá hay tres clases de gente: la que se mata trabajando, las que deberían trabajar y las que tendrían que matarse.','Mario Benedetti '),
('La sonrisa cuesta menos que la electricidad y da más luz.','Proverbio escocés'),
('El que no sabe gozar de la ventura cuando le viene, no debe quejarse si se pasa.','Miguel de Cervantes'),
('El fracaso es una gran oportunidad para empezar otra vez con más inteligencia.','Henry Ford'),
('Es mejor ser rey de tu silencio que esclavo de tus palabras.','William Shakespeare'),
('Avanzando estos tres pasos, llegarás más cerca de los dioses: Primero: Habla con verdad. Segundo: No te dejes dominar por la cólera. Tercero: Da, aunque no tengas más que muy poco que dar.','Buda'),
('Hemos aprendido a volar como los pájaros, a nadar como los peces; pero no hemos aprendido el sencillo arte de vivir como hermanos.','Martin Luther King'),
('Sólo hay dos palancas que muevan a los hombres: el miedo y el interés.','Napoleón I'),
('¿Sufre más aquél que espera siempre que aquél que nunca esperó a nadie?.','Pablo Neruda '),
('Es un milagro que la curiosidad sobreviva a la educación reglada.','Albert Einstein'),
('La mejor manera de librarse de la tentación es caer en ella.','Oscar Wilde'),
('Se alcanza el éxito convirtiendo cada paso en una meta y cada meta en un paso.','C.C. Cortéz'),
('Cuando apuntas con el dedo, recuerda que tres dedos te señalan a ti.','Proverbio inglés'),
('El éxito consiste en vencer el temor al fracaso.','Charles Augustin Sainte-Beuve '),
('Debemos buscar para nuestros males otra causa que no sea Dios.','Platón'),
('La mentira más común es aquella con la que un hombre se engaña a sí mismo. Engañar a los demás es un defecto relativamente vano.','Friedrich Nietzsche'),
('Los que se enamoran de la práctica sin la teoría son como los pilotos sin timón ni brújula, que nunca podrán saber a dónde van.','Leonardo Da Vinci'),
('Cuando la vida te presente razones para llorar, demuéstrale que tienes mil y una razones para reír.','Anónimo'),
('Al final, lo que importa no son los años de vida, sino la vida de los años.','Abraham Lincoln'),
('La vida es muy peligrosa. No por las personas que hacen el mal, sino por las que se sientan a ver lo que pasa.','Albert Einstein'),
('La muerte no nos roba los seres amados. Al contrario, nos los guarda y nos los inmortaliza en el recuerdo. La vida sí que nos los roba muchas veces y definitivamente.','François Mauriac'),
('La vida es aquello que te va sucediendo mientras te empeñas en hacer otros planes.','John Lennon'),
('A veces podemos pasarnos años sin vivir en absoluto, y de pronto toda nuestra vida se concentra en un solo instante.','Oscar Wilde'),
('Estar preparado es importante, saber esperar lo es aún más, pero aprovechar el momento adecuado es la clave de la vida.','Arthur Schnitzler'),
('Aprendí que no se puede dar marcha atrás, que la esencia de la vida es ir hacia adelante. La vida, en realidad, es una calle de sentido único.','Agatha Christie'),
('La vida no se ha hecho para comprenderla, sino para vivirla.','George Santayana'),
('Así como una jornada bien empleada produce un dulce sueño, así una vida bien usada causa una dulce muerte.','Leonardo Da Vinci'),
('La mayor rémora de la vida es la espera del mañana y la pérdida del día de hoy.','Séneca'),
('Lo menos frecuente en este mundo es vivir. La mayoría de la gente existe, eso es todo.','Oscar Wilde'),
('¡Qué pequeñas son mis manos en relación con todo lo que la vida ha querido darme!','Ramón J. Sénder'),
('La vida es un negocio en el que no se obtiene una ganancia que no vaya acompañada de una pérdida.','Arturo Graf'),
('Duerme con el pensamiento de la muerte y levántate con el pensamiento de que la vida es corta.','Proverbio'),
('En tres tiempos se divide la vida: en presente, pasado y futuro. De éstos, el presente es brevísimo; el futuro, dudoso; el pasado, cierto.','Séneca'),
('Los seres humanos no nacen para siempre el día en que sus madres los alumbran, sino que la vida los obliga a parirse a sí mismos una y otra vez.','Gabriel García Márquez '),
('La muerte es algo que no debemos temer porque, mientras somos, la muerte no es y cuando la muerte es, nosotros no somos.','Antonio Machado'),
('Todo hombre paga su grandeza con muchas pequeñeces, su victoria con muchas derrotas, su riqueza con múltiples quiebras.','Giovanni Papini'),
('La muerte es una vida vivida. La vida es una muerte que viene.','Jorge Luis Borges'),
('El hombre no ha sabido organizar un mundo para sí mismo y es un extraño en el mundo que él mismo ha creado.','Alexis Carrel'),
('No se tome la vida demasiado en serio; nunca saldrá usted vivo de ella.','Elbert Hubbard'),
('Alégrate de la vida porque ella te da la oportunidad de amar, de trabajar, de jugar y de mirar a las estrellas.','Henry Van Dyke'),
('La vida es tan corta y el oficio de vivir tan difícil, que cuando uno empieza a aprenderlo, ya hay que morirse.','Ernesto Sábato'),
('El cuerpo humano es el carruaje; el yo, el hombre que lo conduce; el pensamiento son las riendas, y los sentimientos los caballos.','Platón '),
('Los ideales que iluminan mi camino y una y otra vez me han dado coraje para enfrentar la vida con alegría han sido: la amabilidad, la belleza y la verdad.','Albert Einstein'),
('La vida es un juego de probabilidades terribles; si fuera una apuesta no intervendrías en ella.','Tom Stoppard'),
('No basta con pensar en la muerte, sino que se debe tenerla siempre delante. Entonces la vida se hace más solemne, más importante, más fecunda y alegre.','Stefan Zweig'),
('Cuántas muertes más serán necesarias para darnos cuenta de que ya han sido demasiadas.','Bob Dylan'),
('Creo que los animales ven en el hombre un ser igual a ellos que ha perdido de forma extraordinariamente peligrosa el sano intelecto animal, es decir, que ven en él al animal irracional, al animal que ríe, al animal que llora, al animal infeliz.','Friedrich Nietzsche'),
('Temer al amor es temer a la vida, y los que temen a la vida ya están medio muertos.','Bertrand Russell'),
('Un país, una civilización se puede juzgar por la forma en que trata a sus animales.','Mahatma Gandhi '),
('Todo el mundo trata de realizar algo grande, sin darse cuenta de que la vida se compone de cosas pequeñas.','Frank A. Clark'),
('Si el hombre no ha descubierto nada por lo que morir, no es digno de vivir.','Martin Luther King'),
('Me he dedicado a investigar la vida y no sé por qué ni para qué existe.','Severo Ochoa'),
('Una de las glorias de la civilización sería el haber mejorado la suerte de los animales.','Théophile Gautier'),
('Si no conoces todavía la vida, ¿cómo puede ser posible conocer la muerte?','Confucio'),
('Carpe Diem (aprovecha el día presente). Palabras que nos recuerdan que la vida es corta y debemos apresurarnos a gozar de ella.','Horacio'),
('El secreto de la vida es la honestidad y el juego limpio, si puedes simular eso, lo has conseguido.','Groucho Marx'),
('Solamente una vida dedicada a los demás merece ser vivida','Albert Einstein'),
('Vivir en la Tierra es caro pero ello incluye un viaje gratis alrededor del sol cada año.','Anónimo'),
('La vida es fascinante: sólo hay que mirarla a través de las gafas correctas.','Alejandro Dumas'),
('Todo hombre es como la Luna: con una cara oscura que a nadie enseña.','Mark Twain'),
('La naturaleza benigna provee de manera que en cualquier parte halles algo que aprender.','Leonardo Da Vinci'),
('La muerte sólo será triste para los que no han pensado en ella.','Fénelon'),
('El hombre se cree siempre ser más de lo que es, y se estima menos de lo que vale.','Goethe'),
('¿No es la vida cien veces demasiado breve para aburrirnos?','Friedrich Nietzsche'),
('La muerte para los jóvenes es naufragio y para los viejos es llegar a puerto.','Baltasar Gracián'),
('Ciencia es el arte de crear ilusiones convenientes, que el necio acepta o disputa, pero de cuyo ingenio goza el estudioso, sin cegarse ante el hecho de que tales ilusiones son otros tantos velos para ocultar las profundas tinieblas de lo insondable.','Carl Gustav Jung'),
('El universo visible, es decir, la realización o encarnación del pensamiento divino es la causa ocasional de la ciencia.','Juan Valera'),
('La ciencia no es sino una perversión de sí misma a menos que tenga como objetivo final el mejoramiento de la humanidad.','Nikola Tesla'),
('Un ordenador es para mí la herramienta más sorprendente que hayamos ideado. Es el equivalente a una bicicleta para nuestras mentes.','Steve Jobs'),
('La ciencia siempre vale la pena porque sus descubrimientos, tarde o temprano, siempre se aplican.','Severo Ochoa'),
('La ciencia es más que un simple conjunto de conocimientos: es una manera de pensar.','Carl Sagan'),
('El conocimiento si no se sabe aplicar es peor que la ignorancia.','Charles Bukowski'),
('Hay dos cosas infinitas: el Universo y la estupidez humana. Y del Universo no estoy seguro.','Albert Einstein'),
('VTodos somos muy ignorantes. Lo que ocurre es que no todos ignoramos las mismas cosas.','Albert Einstein'),
('Todo nuestro descontento por aquello de lo que carecemos procede de nuestra falta de gratitud por lo que tenemos.','Daniel Defoe'),
('Los vicios vienen como pasajeros, nos visitan como huéspedes y se quedan como amos.','Confucio'),
('El mal no es lo que entra en la boca del hombre, sino lo que sale de ella.','Jesucristo'),
('Cada vez que proveo una plaza vacante, creo cien descontentos y un ingrato.','Luis XV de Francia'),
('Las almas ruines sólo se dejan conquistar con presentes.','Sócrates'),
('El ser capaz de llenar el ocio de una manera inteligente es el último resultado de la civilización.','Bertrand Russell'),
('No se puede ser y no ser algo al mismo tiempo y bajo el mismo aspecto.','Aristóteles'),
('El ignorante, si calla, será tenido por erudito, y pasará por sabio si no abre los labios.','Salomón'),
('Quien no castiga el mal, ordena que se haga.','Leonardo Da Vinci'),
('Odioso para mí, como las puertas del Hades, es el hombre que oculta una cosa en su seno y dice otra.','Homero'),
('Un egoísta es aquel que se empeña en hablarte de sí mismo cuando tú te estas muriendo de ganas de hablarle de ti.','Jean Cocteau'),
('La debilidad de actitud se vuelve debilidad de carácter.','Albert Einstein'),
('Vale más ser cobarde un minuto que muerto el resto de la vida.','Proverbio irlandés'),
('Contra la estupidez, hasta los dioses luchan en vano.','Goethe'),
('Los defectos de un hombre se adecuan siempre a su tipo de mente. Observa sus defectos y conocerás sus virtudes.','Confucio'),
('El que todo lo aplaza no dejará nada concluido ni perfecto.','Demócrito de Abdera '),
('¿Qué ve el ciego, aunque se le ponga una lámpara en la mano?','Proverbio hindú'),
('No desprecies a nadie; un átomo hace sombra.','Pitágoras de Samos '),
('En esta vida algunos hombres nacen mediocres, otros logran mediocridad y a otros la mediocridad les cae encima.','Joseph Heller'),
('Sólo una persona mediocre está siempre en su mejor momento.','William Somerset Maugham '),
('Los cobardes son los que se cobijan bajo las normas.','Jean Paul Sartre'),
('La violencia es miedo de las ideas de los demás y poca fe en las propias.','Antonio Fraguas Forges'),
('Decimos una necedad y a fuerza de repetirla acabamos creyéndola','Voltaire '),
('Avaro es el que no gasta en lo que debe, ni lo que debe, ni cuando debe.','Aristóteles'),
('Quien tiene muchos vicios, tiene muchos amos.','Plutarco'),
('La ignorancia es la carga más pesada. Pero quien lo lleva no lo siente.','Valeriu Butulescu '),
('Lo único en el mundo peor que una mujer es otra.','Aristófanes '),
('Todos somos muy ignorantes. Lo que ocurre es que no todos ignoramos las mismas cosas.','Albert Einstein'),
('Nadie se desembaraza de un hábito o de un vicio tirándolo de una vez por la ventana; hay que sacarlo por la escalera, peldaño a peldaño.','Mark Twain '),
('La violencia es el miedo a los ideales de los demás.','Mahatma Gandhi'),
('Todo nuestro descontento por aquello de lo que carecemos procede de nuestra falta de gratitud por lo que tenemos.','Daniel Defoe'),
('Nadie está libre de decir estupideces, lo malo es decirlas con énfasis.','Michel de Montaigne '),
('La senda de la virtud es muy estrecha y el camino del vicio, ancho y espacioso.','Miguel de Cervantes '),
('Los vicios vienen como pasajeros, nos visitan como huéspedes y se quedan como amos.','Confucio '),
('La probabilidad de hacer mal se encuentra cien veces al día; la de hacer bien una vez al año.','Refrán'),
('En la amistad y en el amor se es más feliz con la ignorancia que con el saber.','William Shakespeare '),
('El mal no es lo que entra en la boca del hombre, sino lo que sale de ella.','Jesucristo '),
('Siempre se repite la misma historia: cada individuo no piensa más que en sí mismo.','Sófocles '),
('Ningún hombre conoce lo malo que es hasta que no ha tratado de esforzarse por ser bueno. Sólo podrás conocer la fuerza de un viento tratando de caminar contra él, no dejándote llevar.','Clive Staples Lewis'),
('Cínico: un hombre que sabe el precio de todo y el valor de nada.','Oscar Wilde'),
('Ojo por ojo y todo el mundo acabará ciego.','Mahatma Gandhi'),
('Una persona perezosa es un reloj sin agujas, siendo inútil tanto si anda como si está parado.','William Cowper'),
('Un necio encuentra siempre otro necio aún mayor que le admira.','Nicolas Boileau '),
('El mundo no está en peligro por las malas personas sino por aquellas que permiten la maldad.','Albert Einstein'),
('Es extraña la ligereza con que los malvados creen que todo les saldrá bien.','Victor Hugo'),
('Cuando el hombre se mira mucho a sí mismo, llega a no saber cuál es su cara y cuál es su careta.','Pío Baroja '),
('Aunque estés solo, no debes decir ni hacer nada malo. Aprende a avergonzarte más ante ti que ante los demás.','Demócrito de Abdera '),
('Desconfío de la incomunicabilidad; es la fuente de toda violencia.','Jean Paul Sartre '),
('Para que triunfe el mal, sólo es necesario que los buenos no hagan nada.','Edmund Burke'),
('Exageráis la hipocresía de los hombres. La mayoría piensa demasiado poco para permitirse el lujo de poder pensar doble.','Marguerite Yourcenar'),
('La enfermedad del ignorante es ignorar su propia ignorancia.','Amos Bronson Alcott '),
('La ingratitud proviene, tal vez, de la imposibilidad de pagar.','Honoré de Balzac'),
('Así corrompe el ocio al cuerpo humano, como se corrompen las aguas si están quedas.','Ovidio'),
('Tengo tres perros peligrosos: la ingratitud, la soberbia y la envidia. Cuando muerden dejan una herida profunda.','Martin Lutero '),
('La crueldad es la fuerza de los cobardes.','Proverbio árabe'),
('Más vale un minuto de vida franca y sincera que cien años de hipocresía.','Ángel Ganivet'),
('Los cobardes mueren muchas veces antes de su verdadera muerte; los valientes prueban la muerte sólo una vez.','William Shakespeare'),
('La tristeza es un don del cielo, el pesimismo es una enfermedad del espíritu.','Amado Nervo'),
('La violencia es el último recurso del incompetente.','Isaac Asimov'),
('La ignorancia es la noche de la mente: pero una noche sin luna y sin estrellas.','Confucio '),
('La violencia crea más problemas sociales que los que resuelve.','Martin Luther King '),
('Lo peor de la ignorancia..es que.. a medida que se prolonga, adquiere confianza.','Anónimo'),
('Ser consciente de la propia ignorancia es un gran paso hacia el saber.','Benjamin Disraeli'),
('Quien no castiga el mal, ordena que se haga.','Leonardo Da Vinci '),
('El ignorante tiene valor; el sabio miedo.','Alberto Moravia'),
('La mediocridad, posiblemente, consiste en estar delante de la grandeza y no darse cuenta.','Gilbert Keith Chesterton '),
('La idiotez es una enfermedad extraordinaria, no es el enfermo el que sufre por ella, sino los demás.','Voltaire'),
('Lo que se obtiene con violencia, solamente se puede mantener con violencia.','Mahatma Gandhi'),
('Un egoísta es aquel que se empeña en hablarte de sí mismo cuando tú te estas muriendo de ganas de hablarle de ti.','Jean Cocteau '),
('La debilidad de actitud se vuelve debilidad de carácter.','Albert Einstein'),
('La crueldad, como cualquier otro vicio, no requiere ningún motivo para ser practicada, apenas oportunidad.','George Eliot'),
('Es ignorancia no saber distinguir entre lo que necesita demostración y lo que no la necesita.','Aristóteles '),
('Una de las ventajas de ser desordenado es que uno está continuamente haciendo nuevos y excitantes descubrimientos.','Thomas Middleton'),
('Lo peor que hacen los malos es obligarnos a dudar de los buenos.','Jacinto Benavente'),
('La hipocresía es el colmo de todas las maldades.','Molière '),
('Al hombre perverso se le conoce en un sólo día; para conocer al hombre justo hace falta más tiempo.','Sófocles'),
('Nadie sabe lo que hace mientras actúa correctamente, pero de lo que está mal uno siempre es consciente.','Goethe'),
('Hay que dejar la vanidad a los que no tienen otra cosa que exhibir.','Honoré de Balzac '),
('La cobardía es la madre de la crueldad.','Michel de Montaigne '),
('Sólo los cobardes son valientes con sus mujeres.','José Hernández'),
('La pereza no es más que el hábito de descansar antes de estar cansado.','Jules Renard'),
('Todos los necios son obstinados y todos los obstinados son necios.','Baltasar Gracián '),
('La ignorancia siempre está dispuesta a admirarse.','Nicolas Boileau '),
('Aconseja al ignorante, te tomará por su enemigo.','Proverbio árabe'),
('La tierra no produce para los ignorantes sino malezas y abrojos','Gaspar Melchor de Jovellanos '),
('La avaricia y la paz se excluyen mutuamente.','Erich Fromm'),
('El mal existe, pero no sin el bien, como la sombra existe, pero no sin la luz.','Alfred de Musset '),
('La victoria lograda por violencia es equivalente a una derrota, porque es momentánea.','Mahatma Gandhi '),
('El que habla a un necio, aunque sea prudente, parecerá también necio.','Eurípides de Salamina '),
('El hombre más irremediablemente estúpido es aquel que ignora su sabiduría.','Isaac Asimov '),
('El tabique que separa la sana autoconfianza de la insana arrogancia es realmente fino.','Haruki Murakami '),
('Dime y lo olvido, enséñame y lo recuerdo, involúcrame y lo aprendo.','Benjamin Franklin'),
('Mira dos veces para ver lo justo. No mires más que una vez para ver lo bello.','Henry F. Amiel'),
('Hay que ser infiel, pero nunca desleal.','Gabriel García Márquez'),
('Todos los problemas tienen la misma raíz: el miedo, que desaparece gracias al amor; pero el amor nos da miedo.','Anónimo'),
('La política es el arte de buscar problemas, encontrarlos, hacer un diagnóstico falso y aplicar después los remedios equivocados.','Groucho Marx '),
('El corazón humano es un instrumento de muchas cuerdas; el perfecto conocedor de los hombres las sabe hacer vibrar todas, como un buen músico.','Charles Dickens'),
('Procuro ser siempre muy puntual, pues he observado que los defectos de una persona se reflejan muy vivamente en la memoria de quien la espera.','Nicolas Boileau'),
('Si ayudo a una sola persona a tener esperanza, no habré vivido en vano.','Martin Luther King'),
('No hay nostalgia peor que añorar lo que nunca jamás sucedió.','Juan Pablo II'),
('Nos equivocamos a menudo en el amor, a menudo herido, a menudo infeliz, pero soy yo quien vivió, y no un ser ficticio, creado por mi orgullo.','George Sand'),
('La felicidad es la certeza de no sentirse perdido.','Jorge Bucay'),
('Es prudente no fiarse por entero de quienes nos han engañado una vez.','René Descartes'),
('El primer beso es mágico, el segundo íntimo, el tercero rutinario.','Raymond Chandler'),
('Si lloras por haber perdido el sol, las lágrimas no te dejarán ver las estrellas.','Rabindranath Tagore'),
('La vida no se ha hecho para comprenderla, sino para vivirla.','George Santayana'),
('A un gran corazón, ninguna ingratitud lo cierra, ninguna indiferencia lo cansa.','Leon Tolstoi '),
('La amistad no puede ir muy lejos cuando ni unos ni otros están dispuestos a perdonarse los pequeños defectos.','Jean de la Bruyere'),
('Aprendí que no se puede dar marcha atrás, que la esencia de la vida es ir hacia adelante. La vida, en realidad, es una calle de sentido único.','Agatha Christie'),
('El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.','Aristóteles'),
('Si no actúas como piensas, vas a terminar pensando como actúas.','Blaise Pascal'),
('La gratitud, como ciertas flores, no se da en la altura y mejor reverdece en la tierra buena de los humildes.','José Martí'),
('Tu tiempo es limitado, de modo que no lo malgastes viviendo la vida de alguien distinto. No quedes atrapado en el dogma, que es vivir como otros piensan que deberías vivir. No dejes que los ruidos de las opiniones de los demás acallen tu propia voz interior. Y, lo que es más importante, ten el coraje para hacer lo que te dicen tu corazón y tu intuición.','Steve Jobs'),
('La única fuerza y la única verdad que hay en esta vida es el amor. El patriotismo no es más que amor, la amistad no es más que amor.','José Martí'),
('La libertad es el derecho que tienen las personas de actuar libremente, pensar y hablar sin hipocresía.','José Martí'),
('Vale más un minuto de pie que una vida de rodillas.','José Martí'),
('Para ir delante de los demás, se necesita ver más que ellos.','José Martí'),
('También a un gran hombre lo puede exasperar una miserable mosca.','José Martí'),
('La felicidad general de un pueblo descansa en la independencia individual de sus habitantes.','José Martí'),
('Ayudar al que lo necesita no sólo es parte del deber, sino de la felicidad.','José Martí'),
('Buscamos la solidaridad no como un fin sino como un medio encaminado a lograr que nuestra América cumpla su misión universal.','José Martí'),
('El que tiene un derecho no obtiene el de violar el ajeno para mantener el suyo.','José Martí'),
('Los bárbaros que todo lo confían a la fuerza y a la violencia, nada construyen, porque sus simientes son de odio.','José Martí'),
('Los hombres son como los astros, que unos dan luz de sí y otros brillan con la que reciben.','José Martí'),
('El lenguaje ha de ser matemático, geométrico, escultórico. La idea ha de encajar exactamente en la frase, tan exactamente que no pueda quitarse nada de la frase sin quitar eso mismo de la idea.','José Martí'),
('Es preferible el bien de muchos a la opulencia de pocos.','José Martí'),
('Mi trabajo es cantar todo lo bello, encender el entusiasmo por todo lo noble, admirar y hacer admirar todo lo grande.','José Martí'),
('La patria es dicha, dolor y cielo de todos y no feudo ni capellanía de nadie.','José Martí'),
('Para pedestal, no para sepulcro, se hizo la tierra, puesto que está tendida a nuestros pies.','José Martí'),
('Los derechos se toman, no se piden; se arrancan, no se mendigan.','José Martí'),
('El único autógrafo digno de un hombre es el que deja escrito con sus obras.','José Martí'),
('Los hombres se dividen en dos bandos: los que aman y fundan, los que odian y deshacen.','José Martí'),
('El elogio oportuno fomenta el mérito, y la falta de elogio lo desanima.','José Martí'),
('Un amigo es uno que lo sabe todo de ti y a pesar de ello te quiere.','Elbert Hubbard '),
('Si sientes que todo perdió su sentido, siempre habrá un ¨te quiero¨, siempre habrá un amigo.','Emerson '),
('La amistad es más difícil y más rara que el amor. Por eso, hay que salvarla como sea.','Alberto Moravia'),
('Ama hasta que te duela. Si te duele es buena señal.','Madre Teresa de Calcuta'),
('Un hermano puede no ser un amigo, pero un amigo será siempre un hermano.','Demetrio de Falero'),
('Te amo para amarte y no para ser amado, puesto que nada me place tanto como verte a ti feliz.','George Sand'),
('En un beso, sabrás todo lo que he callado.','Pablo Neruda'),
('No olvides nunca que el primer beso no se da con la boca, sino con los ojos.','O. K. Bernhardt'),
('Cuando mi voz calle con la muerte, mi corazón te seguirá hablando.','Rabindranath Tagore'),
('La amistad es un alma que habita en dos cuerpos; un corazón que habita en dos almas.','Aristóteles'),
('El amor es: el dolor de vivir lejos del ser amado.','Anónimo'),
('El que busca un amigo sin defectos se queda sin amigos.','Proverbio turco'),
('Uno está enamorado cuando se da cuenta de que otra persona es única.','Jorge Luis Borges'),
('Por muy larga que sea la tormenta, el sol siempre vuelve a brillar entre las nubes.','Khalil Gibran '),
('El verdadero amor es como los espíritus: todos hablan de ellos, pero pocos los han visto.','François de La Rochefoucauld'),
('Los verdaderos amigos se tienen que enfadar de vez en cuando.','Louis Pasteur'),
('La posibilidad de realizar un sueño es lo que hace que la vida sea interesante.','Paulo Coelho'),
('Amar no es solamente querer, es sobre todo comprender.','Françoise Sagan'),
('Lo pasado ha huido, lo que esperas está ausente, pero el presente es tuyo.','Proverbio árabe'),
('Lo bueno de los años es que curan heridas, lo malo de los besos es que crean adicción.','Joaquín Sabina'),
('Ni la ausencia ni el tiempo son nada cuando se ama.','Alfred de Musset'),
('La verdadera amistad es como la fosforescencia, resplandece mejor cuando todo se ha oscurecido.','Rabindranath Tagore'),
('Los amigos que tienes y cuya amistad ya has puesto a prueba / engánchalos a tu alma con ganchos de acero.','William Shakespeare'),
('La amistad duplica las alegrías y divide las angustias por la mitad.','Sir Francis Bacon'),
('Cuando la vida te presente razones para llorar, demuéstrale que tienes mil y una razones para reír.','Anónimo'),
('El que ha conocido sólo a su mujer y la ha amado, sabe más de mujeres que el que ha conocido mil.','Leon Tolstoi '),
('El más difícil no es el primer beso sino el último.','Paul Géraldy '),
('Lo que hoy siente tu corazón, mañana lo entenderá tu cabeza.','Anónimo'),
('Aprendemos a amar no cuando encontramos a la persona perfecta, sino cuando llegamos a ver de manera perfecta a una persona imperfecta.','Sam Keen'),
('La señal de que no amamos a alguien es que no le damos todo lo mejor que hay en nosotros.','Paul Claudel'),
('Nunca desistas de un sueño. Sólo trata de ver las señales que te lleven a él.','Paulo Coelho'),
('Amar no es mirarse el uno al otro; es mirar juntos en la misma dirección.','Antoine de Saint-Exupéry'),
('El hombre y la mujer han nacido para amarse, pero no para vivir juntos. Los amantes célebres de la historia vivieron siempre separados.','Noel Clarasó'),
('La dicha de la vida consiste en tener siempre algo que hacer, alguien a quien amar y alguna cosa que esperar.','Thomas Chalmers'),
('Amar es encontrar en la felicidad de otro tu propia felicidad.','Gottfried Leibniz'),
('Conocer el amor de los que amamos es el fuego que alimenta la vida.','Pablo Neruda'),
('Felicidad no es hacer lo que uno quiere sino querer lo que uno hace.','Jean Paul Sartre'),
('Las cartas de amor se escriben empezando sin saber lo que se va a decir, y se terminan sin saber lo que se ha dicho.','Jean Jacques Rousseau'),
('La gente se arregla todos los días el cabello. ¿Por qué no el corazón?','Proverbio chino'),
('Quien habla mal de mí a mis espaldas mi culo contempla.','Winston Churchill'),
('Si lo que vas a decir no es más bello que el silencio: no lo digas.','Proverbio árabe'),
('Es más fácil quedar bien como amante que como marido; porque es más fácil ser oportuno e ingenioso de vez en cuando que todos los días.','Honoré de Balzac'),
('La mayor declaración de amor es la que no se hace; el hombre que siente mucho, habla poco.','Platón'),
('Un libro abierto es un cerebro que habla; cerrado un amigo que espera; olvidado, un alma que perdona; destruido, un corazón que llora.','Proverbio hindú'),
('El alma que hablar puede con los ojos, también puede besar con la mirada.','Gustavo Adolfo Bécquer'),
('El futuro tiene muchos nombres. Para los débiles es lo inalcanzable. Para los temerosos, lo desconocido. Para los valientes es la oportunidad','Victor Hugo'),
('La felicidad es interior, no exterior; por lo tanto, no depende de lo que tenemos, sino de lo que somos.','Henry Van Dyke '),
('El ignorante afirma, el sabio duda y reflexiona.','Aristóteles'),
('Hay que escuchar a la cabeza, pero dejar hablar al corazón.','Marguerite Yourcenar'),
('En el corazón de todos los inviernos vive una primavera palpitante, y detrás de cada noche, viene una aurora sonriente.','Khalil Gibran '),
('Quien no comprende una mirada tampoco comprenderá una larga explicación.','Proverbio árabe'),
('Cuando quieres realmente una cosa, todo el Universo conspira para ayudarte a conseguirla.','Paulo Coelho'),
('La paciencia es un árbol de raíz amarga pero de frutos muy dulces.','Proverbio persa'),
('Puede uno amar sin ser feliz; puede uno ser feliz sin amar; pero amar y ser feliz es algo prodigioso.','Honoré de Balzac'),
('Si te caes siete veces, levántate ocho.','Proverbio chino'),
('Sólo una cosa vuelve un sueño imposible: el miedo a fracasar.','Paulo Coelho'),
('Al primer amor se le quiere más, a los otros se les quiere mejor.','Antoine de Saint-Exupéry'),
('Ama como puedas, ama a quien puedas, ama todo lo que puedas. No te preocupes de la finalidad de tu amor.','Amado Nervo'),
('Cuando se habla de estar enamorado como un loco se exagera; en general, se está enamorado como un tonto.','Noel Clarasó'),
('No existe el amor, sino las pruebas de amor, y la prueba de amor a aquel que amamos es dejarlo vivir libremente.','Anónimo'),
('El verdadero amigo es aquél que está a tu lado cuando preferiría estar en otra parte.','Len Wein'),
('Nunca consideres el estudio como una obligación, sino como una oportunidad para penetrar en el bello y maravilloso mundo del saber.','Albert Einstein'),
('Besos que vienen riendo, luego llorando se van, y en ellos se va la vida, que nunca más volverá.','Miguel de Unamuno'),
('En la vida no hay premios ni castigos, sino consecuencias.','Robert Green Ingersoll'),
('El verdadero secreto de la felicidad consiste en exigir mucho de sí mismo y muy poco de los otros.','Albert Guinon'),
('La vida es aquello que te va sucediendo mientras te empeñas en hacer otros planes.','John Lennon'),
('No hay que confundir nunca el conocimiento con la sabiduría. El primero nos sirve para ganarnos la vida; la sabiduría nos ayuda a vivir.','Sorcha Carey '),
('A veces podemos pasarnos años sin vivir en absoluto, y de pronto toda nuestra vida se concentra en un solo instante.','Oscar Wilde'),
('El mundo entero se aparta cuando ve pasar a un hombre que sabe adónde va.','Antoine de Saint-Exupéry'),
('No existe nada más interesante que la conversación de dos amantes que permanecen callados.','Achile Tournier'),
('Estar preparado es importante, saber esperar lo es aún más, pero aprovechar el momento adecuado es la clave de la vida.','Arthur Schnitzler'),
('Si no recuerdas la más ligera locura en que el amor te hizo caer, no has amado.','William Shakespeare'),
('Las cadenas de la esclavitud solamente atan las manos: es la mente lo que hace al hombre libre o esclavo.','Franz Grillparzer'),
('Lo que sabemos es una gota de agua; lo que ignoramos es el océano.','Isaac Newton'),
('Es duro, es doloroso, no ser amado cuando se ama todavía, pero es bastante más duro ser todavía amado cuando ya no se ama.','Benjamin Constant'),
('Si supiera que el mundo se acaba mañana, yo, hoy todavía, plantaría un árbol.','Martin Luther King'),
('La decisión del primer beso es la más crucial en cualquier historia de amor, porque contiene dentro de sí la rendición.','Emil Ludwig'),
('Nuestra amistad no depende de cosas como el espacio y el tiempo.','Richard Bach '),
('Ayuda a tus semejantes a levantar su carga, pero no te consideres obligado a llevársela.','Pitágoras de Samos');
